flatpak: Check that flatpak-builder is installed

diff --git a/data/flatpak/org.boum.tails.Platform/build b/data/flatpak/org.boum.tails.Platform/build
--- a/data/flatpak/org.boum.tails.Platform/build
+++ b/data/flatpak/org.boum.tails.Platform/build
@@ -16,6 +16,13 @@ TARGET_DIR="${GIT_TOPLEVEL_DIR}/config/chroot_local-includes/var/lib/flatpak/run
 RUNTIME_DIR=${HOME}/.local/share/flatpak/runtime/org.boum.tails.Platform
 FILES_DIR=${RUNTIME_DIR}/x86_64/stable/active/files/
 
+# Check that the dependencies are installed
+if ! which flatpak-builder >/dev/null; then
+    echo >&2 "Error: flatpak-builder is not installed. Please install it
+ via 'apt install flatpak-builder'".
+    exit 1
+fi
+
 # Check that the working tree is clean, because we automatically commit
 # the changes to the flatpak app to the git repo and we don't want to
 # commit other uncommitted changes.
diff --git a/data/flatpak/org.boum.tails.TorBrowser/build b/data/flatpak/org.boum.tails.TorBrowser/build
--- a/data/flatpak/org.boum.tails.TorBrowser/build
+++ b/data/flatpak/org.boum.tails.TorBrowser/build
@@ -53,6 +53,13 @@ METADATA_FILE="${DIR}/metadata"
 APP_DIR=${HOME}/.local/share/flatpak/app/org.boum.tails.TorBrowser
 FILES_DIR=${APP_DIR}/x86_64/stable/active/files/
 
+# Check that the dependencies are installed
+if ! which flatpak-builder >/dev/null; then
+    echo >&2 "Error: flatpak-builder is not installed. Please install it
+ via 'apt install flatpak-builder'".
+    exit 1
+fi
+
 # Check that the working tree is clean, because we automatically commit
 # the changes to the flatpak app to the git repo and we don't want to
 # commit other uncommitted changes.
